version: '3.8'
services:
  rabbitmq-microservice:
    image: rabbitmq:3.9.10
    restart: always 
    ports:
      - 5672:5672
      - 15672:15672
  
  southconf:
      build:
        context: .
        dockerfile: Southconf/Dockerfile
      restart: always
      stdin_open: true
      volumes:
        - ./Southconf:/southconf
      depends_on:
        - netopeer
      tty: true

  netopeer:
      build:
        context: .
        dockerfile: Netopeer/Dockerfile
      restart: always
      stdin_open: true
      #network_mode: host
      ports:
        - 830:830

  ssh-server:
      build:
        context: .
        dockerfile: sshServer/Dockerfile
      volumes:
        - ./sshServer:/sshserver
      restart: always
      stdin_open: true
      tty: true
      network_mode: host 
      ports:
        - "22:22"
      
